from typing import Union

class ValidationError:
    @property
    def message(self) -> str: ...
    @property
    def path(self) -> str | None: ...
    @property
    def value(self) -> str | None: ...
    @property
    def line(self) -> int | None: ...
    @property
    def column(self) -> int | None: ...

class ValidationResult:
    @property
    def valid(self) -> bool: ...
    @property
    def errors(self) -> list[ValidationError]: ...
    def __bool__(self) -> bool: ...

class Schema:
    def __init__(self, schema: Union[dict, str]) -> None: ...
    def validate_json(self, data_json: str) -> ValidationResult: ...
    def validate_toml(self, data_toml: str) -> ValidationResult: ...
